/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckupRouteImport } from './routes/checkup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ScamsRouteImport } from './routes/scams'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThreatsIndexRouteImport } from './routes/threats/index'
import { Route as ThreatsSlugRouteImport } from './routes/threats/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckupRoute = CheckupRouteImport.update({
  id: '/checkup',
  path: '/checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsRoute = ScamsRouteImport.update({
  id: '/scams',
  path: '/scams',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsIndexRoute = ThreatsIndexRouteImport.update({
  id: '/threats/',
  path: '/threats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsSlugRoute = ThreatsSlugRouteImport.update({
  id: '/threats/$slug',
  path: '/threats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkup': typeof CheckupRoute
  '/contact': typeof ContactRoute
  '/incident': typeof IncidentRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scams': typeof ScamsRoute
  '/terms': typeof TermsRoute
  '/threats/$slug': typeof ThreatsSlugRoute
  '/threats/': typeof ThreatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkup': typeof CheckupRoute
  '/contact': typeof ContactRoute
  '/incident': typeof IncidentRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scams': typeof ScamsRoute
  '/terms': typeof TermsRoute
  '/threats/$slug': typeof ThreatsSlugRoute
  '/threats': typeof ThreatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkup': typeof CheckupRoute
  '/contact': typeof ContactRoute
  '/incident': typeof IncidentRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/safety': typeof SafetyRoute
  '/scams': typeof ScamsRoute
  '/terms': typeof TermsRoute
  '/threats/$slug': typeof ThreatsSlugRoute
  '/threats/': typeof ThreatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkup'
    | '/contact'
    | '/incident'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/resources'
    | '/safety'
    | '/scams'
    | '/terms'
    | '/threats/$slug'
    | '/threats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkup'
    | '/contact'
    | '/incident'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/resources'
    | '/safety'
    | '/scams'
    | '/terms'
    | '/threats/$slug'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkup'
    | '/contact'
    | '/incident'
    | '/learn'
    | '/login'
    | '/privacy'
    | '/privacy-policy'
    | '/resources'
    | '/safety'
    | '/scams'
    | '/terms'
    | '/threats/$slug'
    | '/threats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckupRoute: typeof CheckupRoute
  ContactRoute: typeof ContactRoute
  IncidentRoute: typeof IncidentRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  SafetyRoute: typeof SafetyRoute
  ScamsRoute: typeof ScamsRoute
  TermsRoute: typeof TermsRoute
  ThreatsSlugRoute: typeof ThreatsSlugRoute
  ThreatsIndexRoute: typeof ThreatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkup': {
      id: '/checkup'
      path: '/checkup'
      fullPath: '/checkup'
      preLoaderRoute: typeof CheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams': {
      id: '/scams'
      path: '/scams'
      fullPath: '/scams'
      preLoaderRoute: typeof ScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats/': {
      id: '/threats/'
      path: '/threats'
      fullPath: '/threats/'
      preLoaderRoute: typeof ThreatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats/$slug': {
      id: '/threats/$slug'
      path: '/threats/$slug'
      fullPath: '/threats/$slug'
      preLoaderRoute: typeof ThreatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckupRoute: CheckupRoute,
  ContactRoute: ContactRoute,
  IncidentRoute: IncidentRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  SafetyRoute: SafetyRoute,
  ScamsRoute: ScamsRoute,
  TermsRoute: TermsRoute,
  ThreatsSlugRoute: ThreatsSlugRoute,
  ThreatsIndexRoute: ThreatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
